spring.application.name=My-project9

spring.dataSource.url=jdbc:mysql://localhost:3306/project9

spring.dataSource.username=root
spring.dataSource.password=root

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true





