spring.application.name=My-project16

spring.dataSource.url=jdbc:mysql://localhost:3306/project17
spring.dataSource.username=root
spring.dataSOurce.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
