spring.application.name=JPAProject26

spring.dataSource.url=jdbc:mysql://localhost:3306/jpaproject26

spring.dataSource.username=root
spring.dataSource.password=root

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
