spring.application.name=My-project11

spring.datasource.url=jdbc:mysql://localhost:3306/project12

spring.dataSource.username=root
spring.dataSource.password=root

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

