spring.application.name=My-project24


spring.dataSource.url=jdbc:mysql://localhost:3306/project24

spring.dataSource.username=root
spring.dataSource.password=root

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true	
