spring.application.name=My-project5

spring.datasource.url=jdbc:mysql://localhost:3306/myproject4

spring.dataSource.username=root

spring.dataSource.password=root

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
