spring.application.name=My-project6

spring.datasource.url=jdbc:mysql://localhost:3306/project6

spring.dataSource.username=root
spring.dataSource.password=root

spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.show-sql=true
