spring.application.name=JPAProject25

spring.dataSource.url=jdbc:mysql://localhost:3306/jpaproject25

spring.dataSource.username=root
spring.dataSource.password=root

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true